---
name: Testing

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  pytest:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        python: [3.8, 3.9]
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: ğŸ— Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python }}
      - name: ğŸ— Install dependencies
        run: |
          pip install -r .github/workflows/requirements.txt
          poetry install
      - name: ğŸš€ Run pytest
        run: poetry run pytest --cov elgato tests
      - name: â¬†ï¸ Upload coverage artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: coverage-${{ matrix.python }}-${{ matrix.os }}
          path: .coverage

  coverage:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: â¬‡ï¸ Download coverage data
        uses: actions/download-artifact@v2.0.8
      - name: ğŸ— Set up Python 3.8
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
      - name: ğŸ— Install dependencies
        run: |
          pip install -r .github/workflows/requirements.txt
          poetry install
      - name: ğŸš€ Process coverage results
        run: |
          poetry run coverage combine coverage*/.coverage*
          echo one
          poetry run coverage xml
      - name: ğŸš€ Upload coverage report
        uses: codecov/codecov-action@v1.2.1
