---
name: Testing

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  pytest:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
        python: [3.8, 3.9]
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: ğŸ— Set up Python ${{ matrix.python }}
        id: python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: ${{ matrix.python }}
      - name: â¤µï¸ Restore cached Python virtual environment
        id: cached-poetry-dependencies
        uses: actions/cache@v2.1.4
        with:
          path: .venv
          key: >-
            venv-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
            venv-${{ runner.os }}-${{ steps.python.outputs.python-version }}-
      - name: ğŸ— Install workflow dependencies
        run: |
          pip install -r .github/workflows/requirements.txt
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: ğŸ— Install dependencies
        run: poetry install
      - name: ğŸš€ Run pytest
        run: poetry run pytest --cov elgato tests
      - name: â¬†ï¸ Upload coverage artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: coverage-${{ matrix.python }}-${{ matrix.os }}
          path: .coverage

  coverage:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: â¬‡ï¸ Download coverage data
        uses: actions/download-artifact@v2.0.8
      - name: ğŸ— Set up Python 3.9
        id: python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
      - name: â¤µï¸ Restore cached Python virtual environment
        id: cached-poetry-dependencies
        uses: actions/cache@v2.1.4
        with:
          path: .venv
          key: >-
            venv-${{ runner.os }}-${{ steps.python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}
            venv-${{ runner.os }}-${{ steps.python.outputs.python-version }}-
      - name: ğŸ— Install workflow dependencies
        run: |
          pip install -r .github/workflows/requirements.txt
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
      - name: ğŸ— Install dependencies
        run: poetry install
      - name: ğŸš€ Process coverage results
        run: |
          poetry run coverage combine coverage*/.coverage*
          poetry run coverage xml -i
      - name: ğŸš€ Upload coverage report
        uses: codecov/codecov-action@v1.2.1
